fileID = fopen('../conv_z_vortex/array_conv.txt');
formatSpec = '%f';
conv_arr = fscanf(fileID,formatSpec);
conv_arr = reshape(conv_arr,4,4,4);

% z vortex
figure(1)
semilogy([2;4;6;8],conv_arr(1,:,4),'-s',...
    'MarkerSize',10,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor',[0.73,1.0,1.0],...
    'LineWidth',3,...
    'Color',[0.28,0.46,1.0]);